# System
NUM_PARALLEL_JOBS = -2

# Geographic
CRS_EPSG = 5382

# Raster
RASTER_SCALE_FACTOR = 1 / 4

# Data output
OUTPUT_VECTORS = "data/outputs/vector"
OUTPUT_RASTERS = "data/outputs/raster"
MDS_OUTPUT_FILE = f"{OUTPUT_RASTERS}/K29D6P6_MDS_MVD_025x.tif"
NDVI_OUTPUT_FILE = f"{OUTPUT_RASTERS}/K29D6P6_NDVI_16_Remesa_01_MVD.tif"

# Data input
INPUT_VECTORS = ""
INPUT_RASTERS_IDEUY = "data/ideuy"

MDS_INPUT_FILE = f"{INPUT_RASTERS_IDEUY}/K29D6P6_MDS_Remesa_01_MVD.tif"
MDT_INPUT_FILE = f"{INPUT_RASTERS_IDEUY}/K29D6P6_MDT_Remesa_01_MVD.tif"
RGBI_INPUT_FILE = f"{INPUT_RASTERS_IDEUY}/K29D6P6_RGBI_16_Remesa_01_MVD.tif"
